CREATE DATABASE
IF NOT EXISTS ID_names
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

USE ID_names;

CREATE TABLE
IF NOT EXISTS test
(
area_code MEDIUMINT(6) UNSIGNED NOT NULL DEFAULT 000001,
birth_date DATE,
order_number SMALLINT(3) UNSIGNED NOT NULL DEFAULT 001,
check_number CHAR(1)
);

INSERT INTO test VALUES
(
330183,
'1990-08-25',
001,
'7'
);